### ISSUE TITLE
do you have plan to support Chinese language?

### ISSUE THREAD

**Issue by zhanggaoxuan** [praveshagrawal/Website-2-APK-Builder#1]
do you have plan to support Chinese language?

**Comment by praveshagrawal** [comment]
Yes, sure, We will be glad if you can help us with Chinese Translation.

**Comment by zhanggaoxuan** [comment]
I want to help you translate it into Chinese, how to help you about this?

**Comment by praveshagrawal** [comment]
We need to prepare a list of strings and send it to you, you will need to translate all of them into Chinese and send them back to us. We can also select some translation platform to make it easier, what do you think?

**Comment by praveshagrawal** [comment]
Kindly join us on https://websitetoapk.com/forums/

We will continue our discussion on our website, it will make more people reach to us and join with us to improve it.

**Comment by zhanggaoxuan** [comment]
I can't sign up in the forums, because the CAPTCHA can't show in the website.

select some translation platform maybe is a better choice to translate

**Comment by praveshagrawal** [comment]
Your email please? I will join you.

**Comment by zhanggaoxuan** [comment]
361825255@qq.com

**Comment by praveshagrawal** [comment]
Continue with us https://websitetoapk.com/forums/user/forgot
