### ISSUE TITLE
Trash App

### ISSUE THREAD

**Issue by nissshx** [praveshagrawal/Website-2-APK-Builder#3]
I understand that what you are trying to create is  an app integrated into web view just like proton but its trash. the worst tool I have delivered in years. THe apps doesn't even works! What is the point . Is it that all you know is UI in windows using java, creating windows and such but learn more.

**Comment by nissshx** [comment]
The developer is an idiot

**Comment by praveshagrawal** [comment]
I will certainly help if you can put the error details here.
